'use client';

import { useEffect, useState } from 'react';
import { useAccount, useConnect, useDisconnect } from 'wagmi';
import Link from 'next/link';
import { assets } from '../../lib/assets';
import { explorer } from '../../lib/constants';

export default function Wallet() {
  const { address, isConnected, chainId } = useAccount(); const { connect, connectors } = useConnect(); const { disconnect } = useDisconnect();
  const [history, setHistory] = useState<any[]>([]); const [notice,setNotice]=useState('');
  useEffect(()=>{ if(!address)return; fetch(`/api/executions?wallet=${address}`).then(async r=>{const d=await r.json();if(r.ok)setHistory(d.executions||[]);else setNotice(d.error||'History unavailable.');}).catch(()=>setNotice('History unavailable.')); },[address]);
  return <main className="shell"><nav className="nav"><Link className="brand" href="/">VESTO</Link><div className="navlinks"><Link href="/discover">Discover</Link><Link href="/feed">Feed</Link><Link href="/portfolio">Portfolio</Link><Link href="/wallet">Wallet</Link></div></nav><section className="hero"><div className="eyebrow">BASE WALLET</div><h1>Your positions stay yours.</h1><p className="muted">Connect an injected wallet on Base. Vesto never asks for private keys or takes custody of assets.</p>{isConnected?<><div className="card"><b>Connected</b><p className="muted">{address}</p><p className={chainId===8453?'green':'muted'}>{chainId===8453?'Base mainnet · chain 8453':'Wrong network — switch to Base mainnet before executing.'}</p></div><div className="actions"><Link className="btn primary" href="/portfolio">Open portfolio</Link><button className="btn" onClick={()=>disconnect()}>Disconnect</button></div></>:<div className="actions">{connectors.map(c=><button className="btn primary" key={c.uid} onClick={()=>connect({connector:c})}>Connect {c.name}</button>)}</div>}</section>{isConnected&&<section className="section"><h2>Execution history</h2>{notice&&<p className="muted">{notice}</p>}{history.length===0?<div className="card"><p className="muted">No Vesto executions recorded for this wallet yet. History appears after the optional database is configured and a Vesto execution is confirmed.</p></div>:history.map(x=><div className="card" key={x.tx_hash}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><b>{x.asset_symbol}</b><span className={x.status==='confirmed'?'green':'muted'}>{x.status}</span></div><p className="muted">{new Date(x.created_at).toLocaleString()}</p><a className="green" href={explorer(x.tx_hash)} target="_blank" rel="noreferrer">View on BaseScan ↗</a></div>)}</section>}{isConnected&&<section className="section"><div className="card"><b>Verified asset registry</b>{assets.map(a=><div className="assetrow" key={a.symbol}><div><b>{a.symbol}</b><div className="muted">{a.name}</div></div><a className="green" href={`https://basescan.org/token/${a.address}`} target="_blank" rel="noreferrer">Contract ↗</a></div>)}</div></section>}</main>;
}
